export enum ProfileActionTypes {
    FETCH_PROFILES_FULFILLED = 'FETCH_PROFILES_FULFILLED',
    FETCH_PROFILE_DETAIL_FULLFILLED = 'FETCH_PROFILE_DETAIL_FULLFILLED',
    FETCH_PROFILE_REJECTED = 'FETCH_PROFILE_REJECTED',
    FETCH_PROFILE_PENDING = 'FETCH_PROFILE_PENDING',
    CLEAR_PROFILE_REJECTED = 'CLEAR_PROFILE_REJECTED'
}